ДЗ: Больше деталей
htmlacademy-javascript/1512041-keksobooking-23 pull request #3
Opened 2021-06-09 15:41 UTC by shldvts

2021-06-09 16:39 UTC, AlexMasterov requested changes

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const AUTHOR = 'img/avatars/user0' + getRandomNumber (1, 8) + '.png';
```
Unexpected string concatenation
```
Б11

В этом случае для соединения строки вместо оператора `+` нужно использовать [шаблонные строки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals):

```diff
- 'img/avatars/user0' + getRandomNumber (1, 8) + '.png'
+ `img/avatars/user0${getRandomNumber(1, 8)}.png`
```

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const TYPES = ['palace', 'flat', 'house', 'bungalow', 'hotel',];
```
Unexpected trailing comma 
```
Б11

```diff
- const TYPES = ['palace', 'flat', 'house', 'bungalow', 'hotel',];
+ const TYPES = ['palace', 'flat', 'house', 'bungalow', 'hotel'];
```
Или так:

```js
const TYPES = [
  'palace',
  'flat',
  'house',
  'bungalow',
  'hotel', // <-- comma-dangle
];
```

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const CHECKOUT = ['12:00', '13:00', '14:00',];
`CHECKOUT`

Б5

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const LOCATION = {
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1512041-keksobooking-23/blob/ce4cf87edf5621c0d575ef9aa30ee5d012fb552d/js/main.js#L73-L76
</details>

Объект записан в формате константы, но значения его ключей вычисляются с помощью `getRandomFloat` (= `Math.random()`) и таким образом являются непостоянными.

См. внимательно [учебник с главой про константы](https://up.htmlacademy.ru/javascript/23/book/2.2#:~:text=%D0%9F%D0%BB%D0%BE%D1%85%D0%BE%2C%20%D0%BD%D0%B5%20%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B0%20%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B0%20%D0%BA%D0%B0%D0%BA%20%D0%BA%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B0).

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const getRandomArrayElement = (elements) => {
const getRandomArray`Element` = (`elements`) => {

Для _общего_ случая вместо `Element` и `elements` лучше использовать `Item` и `items`.

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +  return elements[_.random(0, elements.length - 1)];
```
Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>` 
```
Б11

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1512041-keksobooking-23/blob/ce4cf87edf5621c0d575ef9aa30ee5d012fb552d/js/main.js#L80-L82
</details>

Если тело (стрелочной) функции состоит только из одного `return`, то следует использовать короткую запись:

```js
const getRandomArrayElement = (elements) => elements[_.random(0, elements.length - 1)];
```

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const delRandomElementsArray = (someArray, startElement, delQuantity) => {
`someArray`

Б5

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +similarOffers();
```js
main.js:116 Uncaught TypeError: similarOffers is not a function
    at main.js:116
```

[Б2](https://up.htmlacademy.ru/javascript/23/criteries#b2)
> При выполнении кода не возникает необработанных ошибок

```js
Array.isArray(similarOffers) // true
```
Здесь массив используется, как функция (= similarOffers`()`), что некорректно.

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const ADDRESS = ['location.x', 'location.y',];
`ADDRESS`

Б5

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +/* АРХИВ
`//`

Желательно не оставлять закомментированного кода.

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
```
utils/get-random-positive-float.js
utils/get-random-positive-integer.js
```
Все эти модули сейчас не используются, а функции в них почти полностью дублируют функции в модуле `main.js`: `getRandomNumber`, `getRandomFloat`.

[`Д 14`](https://up.htmlacademy.ru/javascript/23/criteries#d14)
> Отсутствует дублирование кода

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const similarOffers = new Array(SIMILAR_OFFER_COUNT).fill(null).map(() => createOffer());
```
img/avatars/user07.png: 10
```
Сейчас изображение для аватара повторяются.

См. задание:
> `avatar`, строка — адрес изображения вида `img/avatars/user{{xx}}.png`, где `{{xx}}` — это число от `1` до `10` с ведущим нулём. Например, 01, 02 и т. д. **Адреса изображений не повторяются**

Нужно исправить.

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const similarOffers = new Array(SIMILAR_OFFER_COUNT).fill(null).map(() => createOffer());
<details>
<summary>advert</summary>

```
avatar: "img/avatars/user07.png"
```
```
checkin: "13:00"
checkout: "13:00"
description: "Лучше места для проживания и не придумать."
features: []
guests: 9
photos: ["https://assets.htmlacademy.ru/content/intensive/ja…ipt-1/keksobooking/claire-rendall-b6kAwr1i0Iw.jpg"]
price: 563989
rooms: 9
title: "Вас также может заинтересовать:"
type: "house"
```
</details>

Сейчас все указанные поля находясь в корне основного объект.

См. внимательно задание:
> Структура каждого объекта должна быть следующей

```js
{
  author,   // объект (.avatar)
  offer,    // объект (.checkin, type, ...)
  location, // объект
}
```


Нужно исправить.

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const similarOffers = new Array(SIMILAR_OFFER_COUNT).fill(null).map(() => createOffer());
```js
const advert1 = similarOffers[0];

typeof advert1.location.lat // string
typeof advert1.location.lng // string
```


См. задание:
> `location`, объект — местоположение в виде географических координат. Состоит из двух полей:

> `lat`, **число с плавающей точкой** — широта, случайное значение от 35.65000 до 35.70000.

> `lng`, **число с плавающей точкой** — долгота, случайное значение от 139.70000 до 139.80000

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1512041-keksobooking-23/blob/ce4cf87edf5621c0d575ef9aa30ee5d012fb552d/js/main.js#L39-L44
https://github.com/htmlacademy-javascript/1512041-keksobooking-23/blob/ce4cf87edf5621c0d575ef9aa30ee5d012fb552d/js/main.js#L74-L75
</details>

Сейчас функция `getRandomFloat` (не смотря на название) вместо _числа_ возвращает _строку_.

Нужно исправить.

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const similarOffers = new Array(SIMILAR_OFFER_COUNT).fill(null).map(() => createOffer());
```js
location: {
  lat: "35.65570",
  lng: "139.70000",
}
```
Сейчас все объекты с предложениями имеют одинаковые координаты (`location`). 

См. задание:
> `location`, объект — местоположение в виде географических координат. Состоит из двух полей:

> `lat`, число с плавающей точкой — широта, **случайное значение** от 35.65000 до 35.70000.

> `lng`, число с плавающей точкой — долгота, **случайное значение** от 139.70000 до 139.80000

Нужно исправить.

2021-06-09 16:39 UTC, AlexMasterov commented on js/main.js
> +const similarOffers = new Array(SIMILAR_OFFER_COUNT).fill(null).map(() => createOffer());
```js
address: [
  "location.x",
  "location.y",
]
```
Сейчас все объекты с предложениями имеют одинаковый `address`, который генерируется неправильно.

См. задание:
> `address`, **строка** — адрес предложения

> Для простоты пусть пока составляется из географических координат по маске `{{location.lat}}`, `{{location.lng}}`

Нужно исправить: координаты из `location` должны совпадать со _строкой_ `offer.address`.

2021-06-10 13:36 UTC, shldvts commented on js/main.js
> +const delRandomElementsArray = (someArray, startElement, delQuantity) => {
Хочу поспорить. 
someArray у меня не массив, а параметр функции.

2021-06-10 13:44 UTC, shldvts commented on js/main.js
> +/* АРХИВ
Не увидел в прошлый раз доп. замечаний к прошлому заданию, исправил.

2021-06-10 13:59 UTC, AlexMasterov commented on js/main.js
> +const delRandomElementsArray = (someArray, startElement, delQuantity) => {
Параметр функции — это её локальная _переменная_, в которую сохраняется значение аргумента при её вызове. Таким образом значения из вне явно попадают в функцию и становятся доступны через параметры.

См. [учебник](https://up.htmlacademy.ru/javascript/23/book/2.7#:~:text=%D0%9F%D0%BE%D1%81%D0%BB%D0%B5%20%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8%20%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8,%D0%B1%D1%83%D0%B4%D0%B5%D1%82%20%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BD%D0%B0%20%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F):
> После имени функции в круглых скобках описываются параметры. Параметры функции — это входные данные. Проще говоря, значения, которые могут быть использованы внутри функций. Параметры передаются в функцию аргументами при вызове, об этом дальше. Для каждого такого значения в теле функции будет доступна **переменная**

> someArray у меня не массив, а параметр функции

На уровне языка доступна только _ссылка_ на массив, которую можно сохранить и передать с помощью _переменных_.

Например, можно увидеть, что _переменная_ `someArray` хранит _ссылку_ на массив: (или тоже самое, но более формально: _значением_ переменной `someArray` является [ссылка на] массив)
```js
Array.isArray(someArray) // true
```

2021-06-10 14:03 UTC, AlexMasterov commented on js/main.js
> +/* АРХИВ
Ничего страшно, по ходу заданий удалим в любом случае 😃

2021-06-12 15:53 UTC, AlexMasterov commented
👍🏻

2021-06-12 15:53 UTC, merged